language: php
php:
- 5.4
- 5.5
- 5.6
before_script: wget https://raw.githubusercontent.com/osTicket/core-plugins/develop/make.php
script: php make.php build auth-cas
deploy:
  provider: releases
  api_key:
    secure: NrFb28kuRSK6r0E6hPgoBIMSvWP7wh5gq5P+X72ASewKJ+mFaHe6dyVWHpyDfDvfsjNoqTF6lHbDcB7lZEncDUS+ZcVbXhB3jbHoCWpBnbliC8j6eEjAt7w/19bQxt620jFJls4e4GCk5hkQ7acVY+YA2htaDKBVKumLmXbHZ55YTWBUE5GlhDVnxu0FffoUpnwc3HgDs6lU2NRrED8JlNG75+bZ9wVqfwVOs8rZm4R2NfGaPTxgRP7FtXyDemzMnc3VKLnKZnfjLiRO7Npj+0Y6eLdupQuwJbYz1pc2mTvk0kB3rTktiA8+494b3BUN/bGld+OPrQJzWnh0XKWKx16iW91usi1N/dAh5W74ePZjeCPP25FUhRjOXFrwKBHmlLUaWyjiAnKrHYF59yyc66ShSp8dWjs6q/42W+gej0C0kohtNMIY4DgkIX1UYf4L8J1YZK7e9WvqxDRgYwCn0MSSbaK0ErV6QXyLmijSnNdaSPSMEn00t+fHG0wclwfcTRffOPOa/BftRU2cVHXkFrxS1mJU1/IIalRLdmgHJY6xQvceeNlXPPbJmPLhVAIncz9YTBFG/S1hRfDqRoedfAkDXw4Dz+7aOa2l+VhI0FT3BrTfnXyVnfvYhAkxA8TZPCwGkEatQ5bAkbctcGXs7kLO8kg70d5ujpDRIWv0lw0=
  file: auth-cas.phar
  skip_cleanup: true
  on:
    repo: kevinoconnor7/osTicket-auth-cas
    tags: true
